const shifts={day:{name:'Dagskift',motors:200},evening:{name:'Kvällsskift',motors:170},night:{name:'Nattskift',motors:100}};
const alerts=[{id:1,severity:'red',type:'ANDON · MATERIALBRIST',title:'Station 12 behöver skruv M8',seconds:300,action:'Skicka truck',material:'Skruv M8',assignee:'Ej tilldelad',stop:'Risk för stopp i cirka 4 minuter',suggestions:['Skicka varning och prioriterat uppdrag till närmaste truckförare.','Genomför förebyggande underhåll eller städning vid stationen medan material inväntas.','Låt lagledaren bedöma om material kan hämtas manuellt.']},{id:2,severity:'amber',type:'VARNING · MATERIAL',title:'Station 07 behöver kabelstam',seconds:1320,action:'Prioritera',material:'Kabelstam A14',assignee:'Truck 3 är närmast'},{id:3,severity:'red',type:'ANDON · TAKTRISK',title:'Station 16 riskerar att tappa takt',seconds:60,action:'Kalla på hjälp',material:'Monteringsmoment',assignee:'Lagledare rekommenderas',takt:true,suggestions:['Stötta station 16 med en extra montör tills takten är återställd.','Förduka kommande material så att montören får kortare hämt- och väntetid.','Låt lagledaren följa upp vilket delmoment som överstiger takttiden.']}];
const tasks=[{id:1,title:'Skruv M8 till station 12',station:'Station 12',level:'Akut',class:'high',status:'Ny',eta:'Behöver starta nu'},{id:2,title:'Kabelstam A14 till station 07',station:'Station 07',level:'Hög',class:'medium',status:'Planerad',eta:'Senast om 14 min'}];
const history=[{station:'Station 04',material:'Clips C3',action:'Levererat av Truck 2',time:'08:19',cause:'Försenad påfyllning'},{station:'Station 11',material:'Handtag',action:'Löst manuellt av lagledare',time:'07:54',cause:''},{station:'Station 09',material:'Taktrisk',action:'Extra montör sattes in',time:'07:31',cause:'Moment tog längre tid än standard'}];
let soundEnabled=false,audioContext,scheduled=60,incidentSeconds=240,incidentActive=false;const $=s=>document.querySelector(s);const time=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`;const critical=a=>a.takt?a.seconds<=60:a.seconds<=300;
function beep(){if(!soundEnabled)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();[880,1040].forEach((f,i)=>setTimeout(()=>{let o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=f;g.gain.setValueAtTime(.08,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.2);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.2)},i*260))}
function render(){let shift=shifts[$('#shift-select').value];$('#shift-status').textContent=`${shift.name} · ${shift.motors} motorer`;$('#shift-title').textContent=shift.name;$('#shift-output').textContent=`${shift.motors} motorer planerade`;
 $('#alerts').innerHTML=alerts.map(a=>`<button class="alert ${critical(a)?'critical':''}" data-alert="${a.id}"><span class="alert-bar ${a.severity}"></span><span class="alert-main"><span class="alert-label">${a.type}${critical(a)?' · AKUT LARM':''}</span><h3>${a.title}</h3><p>${a.takt?'Takttid 03:00 · återstående':'Beräknas ta slut om'} ${time(a.seconds)}</p></span><span class="time ${a.severity}">${time(a.seconds)}</span></button>`).join('');$('#active-count').textContent=`${alerts.length} aktiva`;
 $('#stations').innerHTML=[['03','green','43:00'],['07','amber',time(alerts[1].seconds)],['12','red',time(alerts[0].seconds)],['16','red',time(alerts[2].seconds)],['18','green','51:00'],['21','green','38:00']].map(([n,c,t])=>`<button class="station"><span class="station-top">Station ${n}<i class="dot ${c}"></i></span><strong>${t}</strong><span>till nästa behov</span></button>`).join('');
 $('#tasks').innerHTML=tasks.map(t=>`<article class="task"><div class="task-top"><div><p>${t.station}</p><h3>${t.title}</h3></div><span class="badge ${t.class}">${t.level}</span></div><p>${t.eta}</p><button data-task="${t.id}" class="${t.status==='På väg'?'done':''}">${t.status==='På väg'?'På väg till stationen':'Ta uppdrag'}</button></article>`).join('');
 $('#history').innerHTML=history.map((h,i)=>`<div class="history-item"><div><strong>${h.station} · ${h.material}</strong><span>${h.action}</span><button class="cause-button" data-cause="${i}">${h.cause?'Felorsak: '+h.cause:'+ Lägg till felorsak'}</button></div><span>${h.time}<br>Åtgärdad</span></div>`).join('');
 $('#event-total').textContent=history.length+12;chart('#cause-chart',[['Försenad påfyllning',6],['Truck upptagen',4],['Moment över 3 min',3],['Felaktig materialnivå',2]]);chart('#station-chart',[['Station 12',6],['Station 16',5],['Station 07',3],['Station 04',2]]);chart('#material-chart',[['Skruv M8',6],['Kabelstam A14',4],['Clips C3',3],['Handtag',2]]);updateNext()}
function chart(id,rows){let max=rows[0][1];$(id).innerHTML=rows.map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><strong>${v}</strong></div>`).join('')}
function updateNext(){let n=$('#next-event');n.innerHTML=incidentActive?`<strong class="alert-label">AKUT</strong> Station 05 har materialbrist. Insatsfönster: <strong>${time(incidentSeconds)}</strong>`:`Nästa simulerade materialbrist, station 05: <strong>${time(scheduled)}</strong>`;if(incidentActive)$('#incident-countdown').textContent=time(incidentSeconds)}
function openAlert(id){let a=alerts.find(x=>x.id===id),ideas=a.suggestions?`<section class="suggestion-box"><h3>Förslag till åtgärd</h3>${a.stop?`<p class="stop-risk">${a.stop}</p>`:''}<ul>${a.suggestions.map(s=>`<li>${s}</li>`).join('')}</ul></section>`:'';$('#dialog-type').textContent=a.type;$('#dialog-title').textContent=a.title;$('#dialog-content').innerHTML=`<p>${a.takt?'Takttiden är 03:00. Återstående':'Materialet beräknas ta slut om'} <strong>${time(a.seconds)}</strong>. ${critical(a)?'Detta är ett akut larm.':''}</p><div class="dialog-info"><p><strong>${a.takt?'Takttid':'Material'}:</strong> ${a.takt?'03:00':a.material}</p><p><strong>Rekommendation:</strong> ${a.assignee}</p></div>${ideas}<button class="primary" id="confirm-action">${a.action}</button>`;$('#detail-dialog').showModal();$('#confirm-action').onclick=()=>{$('#detail-dialog').close();toast(`${a.action} registrerad.`)}}
function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function triggerIncident(){incidentActive=true;beep();$('#incident-overlay').classList.remove('hidden');updateNext()}
function tick(){let now=new Date();$('#clock').textContent=now.toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'});alerts.forEach(a=>a.seconds=Math.max(0,a.seconds-1));if(!incidentActive){scheduled--;if(scheduled<=0)triggerIncident()}else incidentSeconds=Math.max(0,incidentSeconds-1);render()}
document.addEventListener('click',e=>{let a=e.target.closest('[data-alert]'),t=e.target.closest('[data-task]'),c=e.target.closest('[data-cause]');if(a)openAlert(+a.dataset.alert);if(t){let x=tasks.find(x=>x.id===+t.dataset.task);x.status='På väg';render();toast(`Uppdrag till ${x.station} är tilldelat dig.`)}if(c){let h=history[+c.dataset.cause];$('#dialog-type').textContent='HISTORIK · DOKUMENTATION';$('#dialog-title').textContent=`${h.station} · ${h.material}`;$('#dialog-content').innerHTML=`<label class="field-label">Felorsak</label><textarea id="cause-input" class="cause-input">${h.cause}</textarea><button class="primary" id="save-cause">Spara felorsak</button>`;$('#detail-dialog').showModal();$('#save-cause').onclick=()=>{h.cause=$('#cause-input').value.trim();$('#detail-dialog').close();render()}}});
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});$('#close-dialog').onclick=()=>$('#detail-dialog').close();$('#close-incident').onclick=()=>$('#incident-overlay').classList.add('hidden');$('#incident-action').onclick=()=>{$('#incident-overlay').classList.add('hidden');toast('Truck 3 och lagledare har bekräftats.')};$('#shift-select').onchange=render;$('#sound-toggle').onclick=async()=>{soundEnabled=!soundEnabled;let b=$('#sound-toggle');if(soundEnabled){audioContext||=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();b.classList.add('enabled');b.textContent='🔔 Ljud aktiverat';beep()}else{b.classList.remove('enabled');b.textContent='🔕 Aktivera ljud'}};render();setInterval(tick,1000);
